services:
  db:
    image: mysql:8.0
    container_name: db-service
    environment:
      MYSQL_DATABASE: imobiscan
      MYSQL_ROOT_PASSWORD: imobiscan_secure_password
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password
    ports:
        - "3306:3306"
    volumes:
        - mysql_data:/var/lib/mysql
        

  nest:
      build:
        context: ./backend-nest
        dockerfile: ./docker/Dockerfile
      container_name: nest-api
      environment:
        - DB_HOST=db
        - DB_USER=root
        - DB_PASSWORD=imobiscan_secure_password
        - DB_NAME=imobiscan
      ports:
        - "3000:3000"
      volumes:
        - ./backend-nest:/usr/src/app
        - nest_node_modules:/usr/src/app/node_modules
      depends_on:
        - db
        - ai-service
        - redis


  ai-service:
    build:
      context: ./backend-python
      dockerfile: docker/Dockerfile
    container_name: ai-python
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=imobiscan_secure_password
      - DB_NAME=imobiscan
    ports:
      - "8000:8000"
    volumes:
      - ./backend-python:/app


  redis:
    image: redis:alpine
    container_name: queue-manager
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-service
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama_data:/var/lib/ollama
    entrypoint: /bin/sh -c "ollama serve & sleep 10 && ollama pull qwen2.5:1.5b && wait"


volumes:
  mysql_data:
  nest_node_modules:
  redis_data:
  ollama_data:
